#! /usr/bin/python3

import unittest
import os
import subprocess
import yaml


class TestAnsibleCheckRun(unittest.TestCase):
    def setUp(self):
        try:
            os.remove("ansible-checks.yml")
        except OSError:
            pass

    def createConf(self, config):
        with open('ansible-checks.yml', 'w') as yaml_file:
                yaml.dump(config, yaml_file, default_flow_style=False)

    def testErrorConfAbsent(self):
        with self.assertRaises(subprocess.CalledProcessError) as context:
            subprocess.check_output('../ansible-checks.py',
                                    stderr=subprocess.STDOUT)

        self.assertTrue("returned non-zero exit status 1"
                        in str(context.exception))

    def testConfSimplePlaybook(self):
        conf = [
            dict(environment="hosts",
                 playbooks=["simple.yml"])
        ]
        self.createConf(conf)

        output = subprocess.check_output('../ansible-checks.py',
                                         stderr=subprocess.STDOUT)

        self.assertEqual("hosts : simple.yml\n", output.decode())

if __name__ == '__main__':
    unittest.main()
