language: python
python:
  - 3.4
  - 3.5
  - 3.6
before_install:
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
  - cd test
install: 
  - pip install -r ../requirements.txt
  - pip install pytest
before_script:
  - pip freeze
script:
  - pytest

