language: python
python:
  - 3.4
  - 3.5
  - 3.6
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-pip
  - sudo pip install ansible 
install: pip install --user -r requirements.txt
script:
  - ansible-checks.py

