language: python
python:
  - 3.4
  - 3.5
  - 3.6
before_install:
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
install: 
  - pip install -r requirements.txt
script:
  - ansible-checks.py

